import type { PrSafetyReport, Verdict } from "./types";

const VERDICT_LABEL: Record<Verdict, string> = {
  merge: "MERGE — No blocking safety signals detected",
  hold: "HOLD — Address the flagged signals before merging",
  split: "SPLIT — Break this PR into smaller, focused changes",
  rebase: "REBASE — Update the branch before merging",
};

/**
 * Render a PR Safety report as GitHub-ready Markdown.
 *
 * Pure formatting of the existing offline report payload — no network calls,
 * no auto-commenting. The user copies or downloads the result themselves.
 */
export function reportToMarkdown(report: PrSafetyReport): string {
  const lines: string[] = [];

  lines.push("# PR Safety Report");
  lines.push("");
  lines.push(`**Verdict:** ${VERDICT_LABEL[report.verdict]}`);
  if (report.title.trim()) {
    lines.push("");
    lines.push(`**PR:** ${report.title.trim()}`);
  }

  // Changed files
  lines.push("");
  lines.push(`## Changed files (${report.changed_files.total})`);
  if (report.changed_files.groups.length === 0) {
    lines.push("");
    lines.push("_No files provided._");
  } else {
    for (const group of report.changed_files.groups) {
      lines.push("");
      lines.push(`### ${group.name}`);
      for (const file of group.files) {
        lines.push(`- \`${file}\``);
      }
    }
  }

  // Risky areas
  lines.push("");
  lines.push(`## Risky areas (status: ${report.risky_areas.status})`);
  if (report.risky_areas.hits.length === 0) {
    lines.push("- No risky areas detected");
  } else {
    for (const hit of report.risky_areas.hits) {
      lines.push(`- **${hit.category}** — \`${hit.file}\`: ${hit.reason}`);
    }
  }

  // Branch freshness
  lines.push("");
  lines.push(`## Branch freshness (status: ${report.branch_freshness.status})`);
  if (report.branch_freshness.commits_behind !== null) {
    const n = report.branch_freshness.commits_behind;
    lines.push(`- ${n} commit${n === 1 ? "" : "s"} behind base`);
  }
  for (const note of report.branch_freshness.notes) {
    lines.push(`- ${note}`);
  }

  // Test coverage
  lines.push("");
  lines.push(`## Test coverage (status: ${report.test_coverage.status})`);
  if (report.test_coverage.gaps.length === 0) {
    lines.push("- No missing test coverage detected for changed source files");
  } else {
    for (const gap of report.test_coverage.gaps) {
      lines.push(`- \`${gap.file}\` — ${gap.reason}`);
    }
  }

  // Scope match
  lines.push("");
  lines.push(`## Scope match (status: ${report.scope_match.status})`);
  if (report.scope_match.notes.length === 0) {
    lines.push("- Changed files line up with the PR title and description");
  } else {
    for (const note of report.scope_match.notes) {
      lines.push(`- ${note}`);
    }
  }

  // Recommendations
  lines.push("");
  lines.push("## Recommendations");
  if (report.recommendations.length === 0) {
    lines.push("- None");
  } else {
    for (const rec of report.recommendations) {
      lines.push(`- ${rec}`);
    }
  }

  lines.push("");
  lines.push("---");
  lines.push("_Generated by Compiler PR Safety — offline heuristic advisory, not merge blocking._");

  return lines.join("\n") + "\n";
}
