"""Parity tests for the Python Markdown port of the web PR Safety renderer.

``app/pr_safety/markdown.py:report_to_markdown`` must mirror
``web/app/pr-safety/markdown.ts:reportToMarkdown`` section-for-section: the
verdict label map, the section headers, the bullet shapes, and the footer.
"""

from __future__ import annotations

from app.pr_safety.markdown import VERDICT_LABEL, report_to_markdown
from app.pr_safety.models import (
    BranchFreshnessSection,
    ChangedFilesSection,
    FileGroup,
    PrSafetyReport,
    RepoAwarePrSafetyReport,
    RepoCommandSignal,
    RepoOwnerMatch,
    RepoSignalsSection,
    RepoStackSignal,
    RepoWorkflowSignal,
    RiskyAreaHit,
    RiskyAreasSection,
    ScopeMatchSection,
    TestCoverageSection,
    TestGapSignal,
)


def _full_report() -> PrSafetyReport:
    return PrSafetyReport(
        verdict="hold",
        title="Add login flow",
        changed_files=ChangedFilesSection(
            total=2,
            groups=[
                FileGroup(name="source", files=["app/auth.py"]),
                FileGroup(name="tests", files=["tests/test_auth.py"]),
            ],
        ),
        risky_areas=RiskyAreasSection(
            status="hit",
            hits=[
                RiskyAreaHit(
                    category="auth",
                    file="app/auth.py",
                    reason="Touches authentication or authorization code",
                )
            ],
        ),
        test_coverage=TestCoverageSection(
            status="gap",
            gaps=[TestGapSignal(file="app/auth.py", reason="missing test")],
            test_files=["tests/test_auth.py"],
        ),
        branch_freshness=BranchFreshnessSection(
            status="ok",
            commits_behind=1,
            notes=["Branch is 1 commits behind the base branch"],
        ),
        scope_match=ScopeMatchSection(status="ok", notes=[]),
        recommendations=["Hold merge until the flagged safety signals are addressed"],
    )


def test_markdown_header_and_verdict_label():
    md = report_to_markdown(_full_report())
    lines = md.split("\n")
    assert lines[0] == "# PR Safety Report"
    assert lines[2] == f"**Verdict:** {VERDICT_LABEL['hold']}"
    assert "**PR:** Add login flow" in lines


def test_verdict_label_map_matches_web():
    assert VERDICT_LABEL == {
        "merge": "MERGE — No blocking safety signals detected",
        "hold": "HOLD — Address the flagged signals before merging",
        "split": "SPLIT — Break this PR into smaller, focused changes",
        "rebase": "REBASE — Update the branch before merging",
    }


def test_markdown_section_headers_present():
    md = report_to_markdown(_full_report())
    assert "## Changed files (2)" in md
    assert "### source" in md
    assert "- `app/auth.py`" in md
    assert "## Risky areas (status: hit)" in md
    assert "- **auth** — `app/auth.py`: Touches authentication or authorization code" in md
    assert "## Branch freshness (status: ok)" in md
    assert "- 1 commit behind base" in md
    assert "## Test coverage (status: gap)" in md
    assert "- `app/auth.py` — missing test" in md
    assert "## Scope match (status: ok)" in md
    assert "- Changed files line up with the PR title and description" in md
    assert "## Recommendations" in md


def test_markdown_footer_and_trailing_newline():
    md = report_to_markdown(_full_report())
    assert md.endswith(
        "---\n_Generated by Compiler PR Safety — offline heuristic advisory, not merge blocking._\n"
    )


def test_singular_commit_phrasing():
    report = _full_report()
    report.branch_freshness.commits_behind = 1
    assert "- 1 commit behind base" in report_to_markdown(report)
    report.branch_freshness.commits_behind = 3
    assert "- 3 commits behind base" in report_to_markdown(report)


def test_empty_report_fallbacks():
    report = PrSafetyReport(
        verdict="merge",
        title="",
        changed_files=ChangedFilesSection(total=0, groups=[]),
        risky_areas=RiskyAreasSection(status="ok", hits=[]),
        test_coverage=TestCoverageSection(status="ok", gaps=[], test_files=[]),
        branch_freshness=BranchFreshnessSection(status="unknown", commits_behind=None, notes=[]),
        scope_match=ScopeMatchSection(status="ok", notes=[]),
        recommendations=[],
    )
    md = report_to_markdown(report)
    assert "_No files provided._" in md
    assert "- No risky areas detected" in md
    assert "- No missing test coverage detected for changed source files" in md
    assert "- None" in md
    # No title line when title is blank.
    assert "**PR:**" not in md


def test_repo_aware_report_adds_advisory_repository_section():
    report = RepoAwarePrSafetyReport(
        **_full_report().model_dump(),
        repo_signals=RepoSignalsSection(
            source="local_checkout",
            owners=[
                RepoOwnerMatch(
                    file="app/auth.py",
                    owners=["@security"],
                    pattern="/app/*",
                    source=".github/CODEOWNERS",
                )
            ],
            overlapping_workflows=[
                RepoWorkflowSignal(
                    path=".github/workflows/ci.yml",
                    name="CI",
                    jobs=["test"],
                    matched_files=["app/auth.py"],
                )
            ],
            detected_commands=[
                RepoCommandSignal(name="test", command="pytest -q", source="Makefile")
            ],
            stacks=[RepoStackSignal(language="python", frameworks=["fastapi"])],
        ),
    )

    md = report_to_markdown(report)

    assert "## Repository signals (advisory)" in md
    assert "`app/auth.py` → @security" in md
    assert "`.github/workflows/ci.yml` (CI)" in md
    assert "`pytest -q` (from `Makefile`)" in md
    assert "python (fastapi)" in md
