import { describe, expect, test } from "vitest";

import { benchmarkReportToMarkdown } from "./benchmarkMarkdown";
import type { BenchmarkData } from "./BenchmarkResults";

const COMPILED_WIN_REPORT: BenchmarkData = {
  raw_output: "Here is a raw answer.",
  compiled_output: "Here is a compiled answer.",
  compiled_prompt: "Rewritten prompt with constraints.",
  winner: "compiled",
  improvement_score: 24,
  model: "openai/gpt-oss-20b",
  metrics: {
    raw_relevance: 6.5,
    compiled_relevance: 8.9,
    raw_clarity: 5.2,
    compiled_clarity: 8.1,
  },
  processing_ms: 812,
};

const RAW_WIN_REPORT: BenchmarkData = {
  raw_output: "Raw wins here.",
  compiled_output: "Compiled underperforms.",
  compiled_prompt: "A rewritten prompt.",
  winner: "raw",
  improvement_score: -12,
  metrics: {
    raw_relevance: 9.1,
    compiled_relevance: 7.0,
    raw_clarity: 8.4,
    compiled_clarity: 7.9,
  },
  processing_ms: 430,
};

const TIE_REPORT: BenchmarkData = {
  raw_output: "Raw output.",
  compiled_output: "Compiled output.",
  compiled_prompt: "Prompt.",
  winner: "tie",
  improvement_score: 0,
  metrics: {
    raw_relevance: 7.0,
    compiled_relevance: 7.0,
    raw_clarity: 6.5,
    compiled_clarity: 6.5,
  },
  processing_ms: 500,
};

describe("benchmarkReportToMarkdown", () => {
  test("renders winner, improvement score, model and metrics table for a compiled win", () => {
    const md = benchmarkReportToMarkdown(COMPILED_WIN_REPORT);

    expect(md).toContain("# Benchmark Report");
    expect(md).toMatch(/\*\*Winner:\*\*\s*COMPILED/);
    expect(md).toContain("**Improvement score:** +24%");
    expect(md).toContain("**Model:** openai/gpt-oss-20b");
    expect(md).toContain("**Processing time:** 812ms");

    expect(md).toContain("## Metrics");
    expect(md).toContain("| Metric | Raw | Compiled | Delta |");
    expect(md).toContain("| Relevance | 6.5 | 8.9 | +2.4 |");
    expect(md).toContain("| Clarity | 5.2 | 8.1 | +2.9 |");
    expect(md).toContain("_Generated by Compiler Benchmark");
  });

  test("renders a negative improvement score without a double sign when raw wins", () => {
    const md = benchmarkReportToMarkdown(RAW_WIN_REPORT);

    expect(md).toMatch(/\*\*Winner:\*\*\s*RAW/);
    expect(md).toContain("**Improvement score:** -12%");
    expect(md).toContain("| Relevance | 9.1 | 7.0 | -2.1 |");
    // no model provided — the line must be omitted entirely, not printed as "undefined"
    expect(md).not.toContain("**Model:**");
    expect(md).not.toContain("undefined");
  });

  test("omits the improvement score line for a tie and still renders metrics", () => {
    const md = benchmarkReportToMarkdown(TIE_REPORT);

    expect(md).toMatch(/\*\*Winner:\*\*\s*TIE/);
    expect(md).not.toContain("**Improvement score:**");
    expect(md).toContain("| Relevance | 7.0 | 7.0 | +0.0 |");
  });

  test("omits the model line when model is an empty or whitespace-only string", () => {
    const md = benchmarkReportToMarkdown({ ...COMPILED_WIN_REPORT, model: "   " });
    expect(md).not.toContain("**Model:**");
  });

  test("ends with a footer line identifying the source", () => {
    const md = benchmarkReportToMarkdown(COMPILED_WIN_REPORT);
    expect(md).toContain("_Generated by Compiler Benchmark");
    expect(md.endsWith("\n")).toBe(true);
  });
});
