import type { BenchmarkData } from "./BenchmarkResults";

const WINNER_LABEL: Record<BenchmarkData["winner"], string> = {
  compiled: "COMPILED — the compiled prompt produced the better output",
  raw: "RAW — the raw prompt produced the better output",
  tie: "TIE — no clear winner",
};

function formatMetricRow(label: string, raw: number, compiled: number): string {
  const delta = compiled - raw;
  const sign = delta >= 0 ? "+" : "";
  return `| ${label} | ${raw.toFixed(1)} | ${compiled.toFixed(1)} | ${sign}${delta.toFixed(1)} |`;
}

/**
 * Render a Benchmark result as GitHub-ready Markdown.
 *
 * Pure formatting of the existing offline benchmark payload — no network calls.
 * The user copies or downloads the result themselves so the evidence (metrics,
 * winner, improvement score, model) can leave the page as more than a screenshot.
 */
export function benchmarkReportToMarkdown(data: BenchmarkData): string {
  const lines: string[] = [];

  lines.push("# Benchmark Report");
  lines.push("");
  lines.push(`**Winner:** ${WINNER_LABEL[data.winner]}`);

  if (data.winner !== "tie") {
    const sign = data.improvement_score >= 0 ? "+" : "";
    lines.push("");
    lines.push(`**Improvement score:** ${sign}${data.improvement_score}%`);
  }

  if (data.model && data.model.trim()) {
    lines.push("");
    lines.push(`**Model:** ${data.model.trim()}`);
  }

  lines.push("");
  lines.push(`**Processing time:** ${data.processing_ms}ms`);

  lines.push("");
  lines.push("## Metrics");
  lines.push("");
  lines.push("| Metric | Raw | Compiled | Delta |");
  lines.push("| --- | --- | --- | --- |");
  lines.push(formatMetricRow("Relevance", data.metrics.raw_relevance, data.metrics.compiled_relevance));
  lines.push(formatMetricRow("Clarity", data.metrics.raw_clarity, data.metrics.compiled_clarity));

  lines.push("");
  lines.push("---");
  lines.push("_Generated by Compiler Benchmark — raw vs. compiled prompt comparison._");

  return lines.join("\n") + "\n";
}
